# Generated by Django 4.0 on 2021-12-15 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.category', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 22, 14, 49, 525050)),
        ),
        migrations.AddField(
            model_name='project',
            name='img1',
            field=models.ImageField(default='photos/%y/%m/%d', upload_to='photos/%y/%m/%d'),
        ),
    ]
