# Generated by Django 4.0 on 2021-12-24 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_project_img2_project_img3_project_img4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='التفاصيل'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 14, 34, 17, 439197)),
        ),
    ]
