# Generated by Django 4.0 on 2021-12-24 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_project_date_time_alter_project_detail_rusul_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rusul',
            old_name='info',
            new_name='Rinfo',
        ),
        migrations.AddField(
            model_name='hussain',
            name='Hprof',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاختصاص'),
        ),
        migrations.AddField(
            model_name='mohammed',
            name='Mprof',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاختصاص'),
        ),
        migrations.AddField(
            model_name='rusul',
            name='Rprof',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاختصاص'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 21, 9, 4, 618954)),
        ),
    ]
