# Generated by Django 4.0 on 2021-12-30 22:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_info_rusul_rinfo_hussain_hprof_mohammed_mprof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 31, 1, 8, 25, 937481)),
        ),
    ]
