# Generated by Django 4.0 on 2022-01-12 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_project_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 12, 18, 41, 47, 705799)),
        ),
    ]
