# Generated by Django 4.0 on 2022-02-13 22:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pages', '0012_alter_project_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MMprof', models.CharField(blank=True, max_length=150, verbose_name='الاختصاص')),
                ('MMinfo', models.TextField(blank=True, max_length=500, verbose_name='المعلومات')),
                ('MMimg', models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='الصورة')),
                ('MMname', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='الاسم')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 14, 1, 7, 37, 866639)),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ptitle', models.CharField(max_length=100, verbose_name='Title')),
                ('Pdetails', models.TextField(null=True, verbose_name='Details')),
                ('Pimg', models.ImageField(upload_to='photos/%y/%m/%d', verbose_name='Image')),
                ('Pdata_time', models.DateTimeField(default=datetime.datetime(2022, 2, 14, 1, 7, 37, 871634))),
                ('Pcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.category', verbose_name='Category')),
                ('Pmember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.members', verbose_name='User')),
            ],
        ),
    ]
