# Generated by Django 4.0 on 2022-09-11 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_members_alter_project_date_time_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='MMname',
            field=models.CharField(blank=True, max_length=150, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='Pdata_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 0, 20, 16, 361467)),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 0, 20, 16, 361467)),
        ),
    ]
